CREATE TABLE IF NOT EXISTS `maktab`.`student_course_results` (
    `StudentCourseResultId` BINARY(16) NOT NULL,
    `StudentCourseEnrollmentId` BINARY(16) NOT NULL,
    `ChildId` BINARY(16) NOT NULL,
    `FamilyId` BINARY(16) NOT NULL,
    `CourseId` BINARY(16) NOT NULL,
    `CourseEnrollmentGroupId` BINARY(16) NOT NULL,
    `InstituteId` BINARY(16) NOT NULL,
    `AttendancePercentage` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    `ResultStatus` INT NOT NULL DEFAULT 0,
    `Remarks` TEXT NULL,
    `RecordedByUserId` BINARY(16) NOT NULL,
    `IsActive` BIT NOT NULL DEFAULT b'1',
    `CreatedAt` DATETIME NOT NULL,
    `UpdatedOn` DATETIME NOT NULL,
    PRIMARY KEY (`StudentCourseResultId`),
    UNIQUE KEY `uq_student_course_results_enrollment` (`StudentCourseEnrollmentId`),
    KEY `idx_student_course_results_family_course` (`FamilyId`, `CourseId`, `IsActive`),
    KEY `idx_student_course_results_child_course` (`ChildId`, `CourseId`, `IsActive`),
    KEY `idx_student_course_results_group_active` (`CourseEnrollmentGroupId`, `IsActive`),
    KEY `idx_student_course_results_recorded_by` (`RecordedByUserId`, `UpdatedOn`)
);

CREATE TABLE IF NOT EXISTS `maktab_dev`.`student_course_results` (
    `StudentCourseResultId` BINARY(16) NOT NULL,
    `StudentCourseEnrollmentId` BINARY(16) NOT NULL,
    `ChildId` BINARY(16) NOT NULL,
    `FamilyId` BINARY(16) NOT NULL,
    `CourseId` BINARY(16) NOT NULL,
    `CourseEnrollmentGroupId` BINARY(16) NOT NULL,
    `InstituteId` BINARY(16) NOT NULL,
    `AttendancePercentage` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    `ResultStatus` INT NOT NULL DEFAULT 0,
    `Remarks` TEXT NULL,
    `RecordedByUserId` BINARY(16) NOT NULL,
    `IsActive` BIT NOT NULL DEFAULT b'1',
    `CreatedAt` DATETIME NOT NULL,
    `UpdatedOn` DATETIME NOT NULL,
    PRIMARY KEY (`StudentCourseResultId`),
    UNIQUE KEY `uq_student_course_results_enrollment` (`StudentCourseEnrollmentId`),
    KEY `idx_student_course_results_family_course` (`FamilyId`, `CourseId`, `IsActive`),
    KEY `idx_student_course_results_child_course` (`ChildId`, `CourseId`, `IsActive`),
    KEY `idx_student_course_results_group_active` (`CourseEnrollmentGroupId`, `IsActive`),
    KEY `idx_student_course_results_recorded_by` (`RecordedByUserId`, `UpdatedOn`)
);
