CREATE TABLE IF NOT EXISTS `maktab`.`student_course_attendance` (
    `StudentCourseAttendanceId` BINARY(16) NOT NULL,
    `StudentCourseEnrollmentId` BINARY(16) NOT NULL,
    `CourseEnrollmentGroupId` BINARY(16) NOT NULL,
    `CourseId` BINARY(16) NOT NULL,
    `InstituteId` BINARY(16) NOT NULL,
    `FamilyId` BINARY(16) NOT NULL,
    `ChildId` BINARY(16) NOT NULL,
    `AttendanceDate` DATE NOT NULL,
    `AttendanceStatus` INT NOT NULL DEFAULT 0,
    `LateArrivalTime` DATETIME NULL,
    `EarlyPickupTime` DATETIME NULL,
    `PickupContactType` INT NOT NULL DEFAULT 0,
    `PickupUserId` BINARY(16) NULL,
    `PickupOtherContactId` BINARY(16) NULL,
    `Notes` TEXT NULL,
    `RecordedByUserId` BINARY(16) NOT NULL,
    `IsActive` BIT NOT NULL DEFAULT b'1',
    `CreatedAt` DATETIME NOT NULL,
    `UpdatedOn` DATETIME NOT NULL,
    PRIMARY KEY (`StudentCourseAttendanceId`),
    UNIQUE KEY `uq_student_course_attendance_enrollment_date` (`StudentCourseEnrollmentId`, `AttendanceDate`),
    KEY `idx_student_course_attendance_group_date` (`CourseEnrollmentGroupId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_course_date` (`CourseId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_child_date` (`ChildId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_family_date` (`FamilyId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_recorded_by` (`RecordedByUserId`, `AttendanceDate`)
);

CREATE TABLE IF NOT EXISTS `maktab_dev`.`student_course_attendance` (
    `StudentCourseAttendanceId` BINARY(16) NOT NULL,
    `StudentCourseEnrollmentId` BINARY(16) NOT NULL,
    `CourseEnrollmentGroupId` BINARY(16) NOT NULL,
    `CourseId` BINARY(16) NOT NULL,
    `InstituteId` BINARY(16) NOT NULL,
    `FamilyId` BINARY(16) NOT NULL,
    `ChildId` BINARY(16) NOT NULL,
    `AttendanceDate` DATE NOT NULL,
    `AttendanceStatus` INT NOT NULL DEFAULT 0,
    `LateArrivalTime` DATETIME NULL,
    `EarlyPickupTime` DATETIME NULL,
    `PickupContactType` INT NOT NULL DEFAULT 0,
    `PickupUserId` BINARY(16) NULL,
    `PickupOtherContactId` BINARY(16) NULL,
    `Notes` TEXT NULL,
    `RecordedByUserId` BINARY(16) NOT NULL,
    `IsActive` BIT NOT NULL DEFAULT b'1',
    `CreatedAt` DATETIME NOT NULL,
    `UpdatedOn` DATETIME NOT NULL,
    PRIMARY KEY (`StudentCourseAttendanceId`),
    UNIQUE KEY `uq_student_course_attendance_enrollment_date` (`StudentCourseEnrollmentId`, `AttendanceDate`),
    KEY `idx_student_course_attendance_group_date` (`CourseEnrollmentGroupId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_course_date` (`CourseId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_child_date` (`ChildId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_family_date` (`FamilyId`, `AttendanceDate`, `IsActive`),
    KEY `idx_student_course_attendance_recorded_by` (`RecordedByUserId`, `AttendanceDate`)
);
